// // Copyright 2018-present the Flutter authors. All Rights Reserved.
// //
// // Licensed under the Apache License, Version 2.0 (the "License");
// // you may not use this file except in compliance with the License.
// // You may obtain a copy of the License at
// //
// // http://www.apache.org/licenses/LICENSE-2.0
// //
// // Unless required by applicable law or agreed to in writing, software
// // distributed under the License is distributed on an "AS IS" BASIS,
// // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// // See the License for the specific language governing permissions and
// // limitations under the License.

// import 'product.dart';


// class ProductsRepository {
//   static List<Product> loadProducts(Category category) {
//     List<Product> allProducts = [
//       Product(
//         category: Category.accessories,
//         id: 0,
//         isFeatured: 3,
//         name: 'A hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-5678',
//         descrip: 'beautiful hotel',
//       ),
//       Product(
//         category: Category.accessories,
//         id: 1,
//         isFeatured: 3,
//         name: 'B hotel',
//         address: 'Berlin',
//         phonenum: '010-1234-5679',
//         descrip: 'wonderful hotel',
//       ),
//       Product(
//         category: Category.accessories,
//         id: 2,
//         isFeatured: 5,
//         name: 'C hotel',
//         address: 'Gyeongsangbuk-do',
//         phonenum: '010-1234-1111',
//         descrip: 'Welcome to my hotel',
//       ),
//       Product(
//         category: Category.accessories,
//         id: 3,
//         isFeatured: 4,
//         name: 'D hotel',
//         address: 'Ave',
//         phonenum: '010-1234-2222',
//         descrip: 'Have a nice day~',
//       ),
//       Product(
//         category: Category.accessories,
//         id: 4,
//         isFeatured: 3,
//         name: 'E hotel',
//         address: 'Warszawa,0982',
//         phonenum: '010-1234-3333',
//         descrip: 'Have a GOODDAY~!~!',
//       ),
//       Product(
//         category: Category.accessories,
//         id: 5,
//         isFeatured: 2,
//         name: 'F hotel',
//         address: '45, Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'HELLO',
//       ),
//       Product(
//         category: Category.accessories,
//         id: 6,
//         isFeatured: 4,
//         name: 'G hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.accessories,
//         id: 7,
//         isFeatured: 4,
//         name: 'H hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'Have a GOODDAY~!~!',
//       ),
//       Product(
//         category: Category.accessories,
//         id: 8,
//         isFeatured: 5,
//         name: 'I hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 9,
//         isFeatured: 1,
//         name: 'J hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 10,
//         isFeatured: 3,
//         name: 'K hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 11,
//         isFeatured: 4,
//         name: 'L hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 12,
//         isFeatured: 5,
//         name: 'M hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 13,
//         isFeatured: 3,
//         name: 'N hotel',
//         address: 'Warszawa,979-55',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 14,
//         isFeatured: 4,
//         name: 'O hotel',
//         address: 'Warszawa,00-987',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 15,
//         isFeatured: 5,
//         name: 'P hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 16,
//         isFeatured: 2,
//         name: 'Q hotel',
//         address: 'Warszawa,',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 17,
//         isFeatured: 3,
//         name: 'R hotel',
//         address: 'Warszawa,0101',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.home,
//         id: 18,
//         isFeatured: 4,
//         name: 'S hotel',
//         address: 'Warszawa,356',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 19,
//         isFeatured: 4,
//         name: 'T hotel',
//         address: 'Warszawa,123',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 20,
//         isFeatured: 5,
//         name: 'U hotel',
//         address: 'Warszawa,5970',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 21,
//         isFeatured: 2,
//         name: 'V hotel',
//         address: 'Warszawa,kml',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 22,
//         isFeatured: 1,
//         name: 'W hotel',
//         address: 'Warszawa,kk',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 23,
//         isFeatured: 4,
//         name: 'X hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 24,
//         isFeatured: 4,
//         name: 'Y hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 25,
//         isFeatured: 2,
//         name: 'Z hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 26,
//         isFeatured: 3,
//         name: 'a hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 27,
//         isFeatured: 4,
//         name: 'b hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 28,
//         isFeatured: 4,
//         name: 'c hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 29,
//         isFeatured: 4,
//         name: 'd hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Hello',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 30,
//         isFeatured: 4,
//         name: 'e hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3033',
//         descrip: 'abcd',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 31,
//         isFeatured: 3,
//         name: 'f hotel',
//         address: 'Ave',
//         phonenum: '010-1234-0101',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 32,
//         isFeatured: 3,
//         name: 'g hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 33,
//         isFeatured: 3,
//         name: 'h hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 34,
//         isFeatured: 3,
//         name: 'i hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 35,
//         isFeatured: 4,
//         name: 'j hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 36,
//         isFeatured: 4,
//         name: 'k hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//       Product(
//         category: Category.clothing,
//         id: 37,
//         isFeatured: 5,
//         name: 'l hotel',
//         address: 'Ave',
//         phonenum: '010-1234-3333',
//         descrip: 'Nice to Meet you',
//       ),
//     ];
//     if (category == Category.all) {
//       return allProducts;
//     } else {
//       return allProducts.where((Product p) {
//         return p.category == category;
//       }).toList();
//     }
//   }
// }
